version: '3'

services:
  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
  storeDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3307:3306
  authenticationDatabaseMigration:
    image: authenticationdatabasemigration
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      authenticationDatabase:
        condition: service_healthy
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDatabase
    depends_on:
      - authenticationDatabaseMigration
    ports:
      - 5000:5000
#  storeOwner:
#    image: storeowner
#    environment:
#      - DATABASE_URL=authenticationDatabase
#    depends_on:
#      storeDatabase:
#        condition: service_healthy
#    ports:
#      - 5001:5001
